# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
before:
  hooks:
    - go mod tidy

archives:
  - id: default
    files:
      - zsh-fast-alias-tips.plugin.zsh

builds:
  - main: cmd/zsh-alias-matcher/main.go
    binary: zsh-alias-matcher
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

source:
  enabled: false
